#!/bin/sh
# shellcheck disable=SC2039
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTDIR="$DIR/dotfiles"
DOTFILES="$HOME/dotfiles"
DOTLIST="$DOTFILES/configfiles.json"
SYNCPY="$DOTFILES/sync.py"
NVIMCONFDIR=".local/share/nvim/site"
VIMDIR="$DOTDIR/$NVIMCONFDIR"

DOCKCMD="docker"
# Prefer podman if installed
if [ -x "$(command -v podman)" ]; then
	DOCKCMD="podman"
fi

if [ -d dotfiles ]; then
    if [ -f "$SYNCPY" ]; then
		echo "Running sync.py -c -t \"$DOCKCMD\" -p \"$DOTDIR\" -l \"$DOTLIST\" ..."
		"$SYNCPY" -c -t $DOCKCMD -p "$DOTDIR" -l "$DOTLIST" || exit 1
	fi
	# Now install vim-plug
	# Copy if exists in the $HOME directory, otherwise - download
	VIMPLUG="$HOME/$NVIMCONFDIR/autoload/plug.vim"
	if [ -f "$VIMPLUG" ]; then
		echo "Using the local Plug.vim copy"
		cp "$VIMPLUG" "$VIMDIR/autoload/plug.vim" || exit 1
	else
		curl -fLo "$VIMDIR/autoload/plug.vim" --create-dirs \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim || exit 1
	fi
fi

"$DOCKCMD" build -t alpine-dev .
